/** Extracted from App.js — preset stile video (Video libero: visivo + regia). */
export const VIDEO_VISUAL_STYLE_PRESETS = [
  {
    id: "realistic",  tag: "@realistico", label: "Realistico",     icon: "📷",
    thumbnailImage: "realistic.jpg",
    thumbnailPrompt: "close-up portrait of a human face, photorealistic DSLR photo, natural skin texture, clean background, premium lighting, highly legible thumbnail composition",
    thumbnailNegativePrompt: "ugly face, deformed anatomy, animal, anthropomorphic, mascot, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "subtle natural movement, stable camera, realistic body motion",
    prompt: "photorealistic live-action video, natural lighting, true-to-life skin texture, realistic materials, balanced contrast, subtle depth of field, clean cinematic realism",
    motion_prompt: "stable handheld or tripod shot, natural subject movement, realistic body mechanics, smooth temporal consistency, no exaggerated motion",
    negative_prompt: "cartoon, anime, stylized CGI, rubbery motion, flickering details, animal, anthropomorphic, furry, mascot, creature, non-human", category: "photo",
  },
  {
    id: "cinematic",  tag: "@cinematico", label: "Cinematico",     icon: "🎬",
    thumbnailImage: "cinematic.jpg",
    thumbnailPrompt: "cinematic movie frame, moody neon alley, dramatic lighting, anamorphic feel, strong composition, premium color grading, highly legible thumbnail",
    thumbnailNegativePrompt: "ugly face, animal, mascot, cartoon, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "slow dolly movement, cinematic parallax, controlled framing",
    prompt: "cinematic live-action film look, dramatic lighting, rich color grading, soft film grain, high contrast, atmospheric depth, anamorphic visual language",
    motion_prompt: "slow cinematic dolly, controlled camera drift, deliberate framing, smooth parallax, natural motion blur, film-like pacing",
    negative_prompt: "flat lighting, cartoon style, shaky amateur footage, hyperactive movement, animal, anthropomorphic, furry, mascot, creature, non-human", category: "photo",
  },
  {
    id: "fashion",    tag: "@fashion",    label: "Fashion",         icon: "👠",
    thumbnailImage: "fashion.jpg",
    thumbnailPrompt: "fashion editorial model in bold outfit, studio backdrop, premium magazine lighting, elegant pose, clean luxury composition, highly legible thumbnail",
    thumbnailNegativePrompt: "ugly face, deformed anatomy, animal, mascot, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "graceful pose transition, slow tracking shot, premium editorial motion",
    prompt: "luxury fashion film, editorial styling, polished skin detail, premium studio or runway lighting, high-end magazine aesthetic, elegant composition, glossy commercial finish",
    motion_prompt: "confident runway-like movement, slow tracking camera, graceful turns, controlled pose transitions, smooth elegant motion",
    negative_prompt: "gritty realism, messy framing, casual phone-video look, distorted anatomy, animal, anthropomorphic, furry, mascot, creature", category: "photo",
  },
  {
    id: "portrait",   tag: "@ritratto",   label: "Ritratto",        icon: "🧑",
    thumbnailImage: "portrait.jpg",
    thumbnailPrompt: "human portrait close-up, rembrandt lighting, dramatic cheek light triangle, shallow depth of field, premium studio realism, highly legible thumbnail",
    thumbnailNegativePrompt: "ugly face, deformed anatomy, animal, mascot, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "subtle blinking, breathing, slight push-in camera",
    prompt: "portrait-focused live-action video, flattering facial light, natural skin detail, soft background separation, intimate framing, refined contrast, premium portrait cinematography",
    motion_prompt: "subtle head movement, blinking, breathing, slight camera push-in, gentle handheld micro-motion, stable face consistency",
    negative_prompt: "wide action shot, exaggerated gestures, cartoon rendering, face flicker, animal, anthropomorphic, furry, mascot, creature", category: "photo",
  },
  {
    id: "vintage",    tag: "@vintage",    label: "Vintage",         icon: "📼",
    thumbnailImage: "vintage.jpg",
    thumbnailPrompt: "1970s vintage photo look, retro subject, faded Kodak tones, analog grain, nostalgic composition, highly legible thumbnail",
    thumbnailNegativePrompt: "modern digital look, neon palette, animal, mascot, cluttered background, text, watermark",
    thumbnailMotionPrompt: "gentle handheld drift, analog cadence, subtle gate weave",
    prompt: "1970s vintage film look, faded Kodak tones, analog texture, visible grain, subtle color shift, nostalgic exposure, retro documentary mood",
    motion_prompt: "gentle handheld drift, old film cadence, slight gate weave feel, imperfect natural motion, restrained pacing",
    negative_prompt: "ultra-clean digital look, neon cyberpunk palette, sterile CGI, modern smartphone sharpness, animal, anthropomorphic, furry, mascot", category: "photo",
  },
  {
    id: "noir",       tag: "@noir",       label: "Film Noir",       icon: "🕵️",
    thumbnailImage: "noir.jpg",
    thumbnailPrompt: "film noir silhouette, black and white, cigarette smoke, hard shadows, detective mood, dramatic contrast, highly legible thumbnail",
    thumbnailNegativePrompt: "color, animal, mascot, cluttered background, text, watermark, blurry, cheerful mood",
    thumbnailMotionPrompt: "slow suspenseful movement, drifting smoke, lingering composition",
    prompt: "classic noir film look, black and white cinematography, hard key light, deep shadows, smoky atmosphere, dramatic silhouettes, high-contrast monochrome tension",
    motion_prompt: "slow suspenseful camera movement, shadow-driven staging, restrained actor motion, lingering compositions, moody cinematic timing",
    negative_prompt: "bright colors, cheerful tone, flat daylight, glossy fashion look, animal, anthropomorphic, furry, mascot", category: "photo",
  },
  {
    id: "anime",      tag: "@anime",      label: "Anime",           icon: "🌸",
    thumbnailImage: "anime.jpg",
    thumbnailPrompt: "anime human face close-up, expressive eyes, clean cel shading, crisp linework, vibrant controlled colors, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, live-action, animal, anthropomorphic, furry, mascot, creature, blurry, text, watermark",
    thumbnailMotionPrompt: "smooth keyframe feel, expressive pose timing, stylized motion",
    prompt: "anime-style animation of a human character, clean cel shading, expressive eyes, crisp linework, stylized human anatomy, polished 2D character aesthetic",
    motion_prompt: "smooth stylized character motion, expressive poses, clean keyframe animation feel, dynamic framing, readable silhouette changes",
    negative_prompt: "photorealistic, live-action, realistic skin pores, animal, anthropomorphic, furry, mascot, creature, non-human, snout, hooves, beak", category: "illustration",
  },
  {
    id: "ghibli",     tag: "@ghibli",     label: "Ghibli",          icon: "🌿",
    thumbnailImage: "ghibli.jpg",
    thumbnailPrompt: "soft hand-painted human character or poetic landscape, gentle watercolor textures, dreamy natural light, storybook feeling, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, hard CGI, animal, anthropomorphic, furry, mascot, monster, blurry, text, watermark",
    thumbnailMotionPrompt: "gentle environmental drift, poetic pacing, lyrical movement",
    prompt: "hand-painted animated illustration of a human character, soft watercolor textures, whimsical atmosphere, airy backgrounds, delicate linework, dreamlike natural lighting",
    motion_prompt: "gentle lyrical motion, soft environmental movement, floating camera drift, calm pacing, poetic animated timing",
    negative_prompt: "hard CGI, gritty realism, harsh neon contrast, animal, anthropomorphic, furry, mascot, creature, non-human", category: "illustration",
  },
  {
    id: "manga",      tag: "@manga",      label: "Manga",           icon: "🖋️",
    thumbnailImage: "manga.jpg",
    thumbnailPrompt: "manga human face close-up, black and white ink, screentone, sharp linework, graphic contrast, highly legible thumbnail",
    thumbnailNegativePrompt: "color, photorealistic, animal, anthropomorphic, furry, mascot, creature, blurry, text, watermark",
    thumbnailMotionPrompt: "sharp pose changes, graphic pauses, impact timing",
    prompt: "black and white manga animation of a human character, inked line art, screentone shading, strong graphic contrast, speed-line energy, dynamic composition",
    motion_prompt: "stylized panel-to-panel motion, sharp pose changes, dramatic pauses, impact timing, graphic directional movement",
    negative_prompt: "full color realism, watercolor painting, glossy 3D render, animal, anthropomorphic, furry, mascot, creature, non-human", category: "illustration",
  },
  {
    id: "comic",      tag: "@fumetto",    label: "Fumetto",         icon: "💥",
    thumbnailImage: "comic.jpg",
    thumbnailPrompt: "western comic hero portrait, bold ink outlines, dramatic foreshortening, flat graphic colors, punchy composition, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, watercolor, animal, anthropomorphic, furry, mascot, creature, blurry, text, watermark",
    thumbnailMotionPrompt: "dynamic action beat, punchy camera angle, strong motion arc",
    prompt: "western comic book animation of a human character, bold inked outlines, flat graphic colors, dramatic action shading, heroic composition, punchy graphic energy",
    motion_prompt: "dynamic action poses, comic-style impact beats, strong camera angles, energetic motion arcs, punchy transitions",
    negative_prompt: "photorealistic, watercolor softness, muted realism, animal, anthropomorphic, furry, mascot, creature, non-human", category: "illustration",
  },
  {
    id: "cartoon",    tag: "@cartoon",    label: "Cartoon",         icon: "🎨",
    thumbnailImage: "cartoon.jpg",
    thumbnailPrompt: "cartoon human character portrait, simple shapes, bright colors, clean outlines, expressive face, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, gritty realism, animal, anthropomorphic, furry, mascot, creature, blurry, text, watermark",
    thumbnailMotionPrompt: "bouncy expressive motion, playful timing, squash-and-stretch feel",
    prompt: "cartoon animation of a human character, simplified human proportions, clean outlines, bright saturated colors, expressive face, smooth shading, polished animated-show look",
    motion_prompt: "bouncy stylized motion, squash-and-stretch feel, expressive timing, playful camera movement, readable exaggerated gestures",
    negative_prompt: "photorealistic, gritty lighting, naturalistic motion, fine skin detail, animal, anthropomorphic, furry, mascot, creature, non-human, snout, hooves, beak, tail", category: "illustration",
  },
  {
    id: "chibi",      tag: "@chibi",      label: "Chibi",           icon: "🧸",
    thumbnailImage: "chibi.jpg",
    thumbnailPrompt: "chibi human character, oversized head, tiny body, huge eyes, kawaii design, clean pastel colors, highly legible thumbnail",
    thumbnailNegativePrompt: "realistic anatomy, photorealistic, animal, anthropomorphic, furry, mascot, creature, blurry, text, watermark",
    thumbnailMotionPrompt: "cute bouncy movement, tiny fast steps, playful looping gesture",
    prompt: "chibi kawaii human character animation, oversized head, tiny body, huge expressive eyes, simplified human anatomy, soft shading, clean colorful design",
    motion_prompt: "cute bouncy movement, tiny fast steps, expressive head tilts, playful looping gestures, cheerful stylized timing",
    negative_prompt: "realistic anatomy, mature proportions, photorealistic skin, animal, anthropomorphic, furry, mascot, creature, non-human", category: "illustration",
  },
  {
    id: "pixel",      tag: "@pixel",      label: "Pixel Art",       icon: "🕹️",
    thumbnailImage: "pixel.jpg",
    thumbnailPrompt: "pixel art 16-bit character or tiny landscape, crisp square pixels, limited color palette, retro game readability, highly legible thumbnail",
    thumbnailNegativePrompt: "smooth gradients, photorealistic, blurry, painterly texture, text, watermark",
    thumbnailMotionPrompt: "limited frame retro motion, sprite-like loop, simple readable movement",
    prompt: "pixel art animation, 16-bit retro game aesthetic, crisp square pixels, limited color palette, sprite-like readability, nostalgic arcade visual style",
    motion_prompt: "frame-by-frame sprite animation feel, simple looping movement, tile-based readability, limited-frame retro motion",
    negative_prompt: "smooth gradients, photorealism, anti-aliased edges, painterly texture, realistic skin, animal realism", category: "illustration",
  },
  {
    id: "disney",     tag: "@disney",     label: "Disney/Pixar",    icon: "✨",
    thumbnailImage: "disney.jpg",
    thumbnailPrompt: "stylized 3D human character portrait, expressive face, polished CGI, soft global illumination, premium family animation look, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, gritty realism, animal, anthropomorphic, furry, mascot, creature, non-human, blurry, text, watermark",
    thumbnailMotionPrompt: "expressive facial acting, smooth body language, polished animation timing",
    prompt: "stylized animated 3D human character, expressive human face, polished CGI, soft global illumination, appealing human proportions, glossy materials, high-end family animation finish",
    motion_prompt: "smooth character animation, expressive facial acting, appealing body language, cinematic camera movement, polished studio-animation timing",
    negative_prompt: "photorealistic skin, gritty live-action, flat 2D line art, uncanny facial motion, animal, anthropomorphic animal, furry, mascot, llama, deer, fox, creature, non-human", category: "3d",
  },
  {
    id: "3d",         tag: "@3d",         label: "3D Render",       icon: "🧊",
    thumbnailImage: "3d.jpg",
    thumbnailPrompt: "clean 3D render of a simple object or bust, glossy materials, soft studio lighting, polished CGI, highly legible thumbnail",
    thumbnailNegativePrompt: "flat 2D illustration, watercolor, sketch, animal, mascot, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "smooth virtual camera drift, polished CGI motion, controlled parallax",
    prompt: "high-end 3D rendered video, physically based materials, global illumination, ray-traced reflections, subsurface scattering, clean geometry, cinematic CGI detail",
    motion_prompt: "smooth virtual camera movement, stable object motion, polished CGI animation, controlled parallax, high temporal consistency",
    negative_prompt: "hand-drawn linework, painterly brushstrokes, photochemical film grain, animal mascot, furry creature", category: "3d",
  },
  {
    id: "clay",       tag: "@clay",       label: "Claymation",      icon: "🪵",
    thumbnailImage: "clay.jpg",
    thumbnailPrompt: "claymation human figure, handmade clay texture, tactile imperfections, miniature set feel, soft lighting, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, hyper-clean CGI, metallic realism, animal, mascot, creature, blurry, text, watermark",
    thumbnailMotionPrompt: "slightly stepped stop-motion cadence, handmade movement timing",
    prompt: "claymation human character design, handcrafted clay texture, tactile surface detail, visible imperfections, miniature set design, charming handmade animation aesthetic",
    motion_prompt: "stop-motion cadence, slightly stepped movement, handmade pose changes, tactile miniature camera feel, playful imperfect timing",
    negative_prompt: "smooth realistic skin, hyper-clean CGI, glossy metallic realism, animal, anthropomorphic, furry, mascot, creature, non-human", category: "3d",
  },
  {
    id: "isometric",  tag: "@isometrico", label: "Isometrico",      icon: "📐",
    thumbnailImage: "isometric.jpg",
    thumbnailPrompt: "isometric miniature room diorama, clean geometry, top-down three-quarter view, architectural clarity, highly legible thumbnail",
    thumbnailNegativePrompt: "eye-level camera, fisheye, cluttered background, text, watermark, blurry, photorealistic",
    thumbnailMotionPrompt: "slow isometric camera drift, miniature scene movement, precise readability",
    prompt: "isometric miniature world, clean modular geometry, diorama design, tiny environmental storytelling, polished scale-model aesthetic, precise architectural layout",
    motion_prompt: "slow isometric camera drift, top-down three-quarter view, miniature scene motion, precise spatial readability, no dramatic perspective shift",
    negative_prompt: "eye-level perspective, fisheye lens, chaotic handheld movement, extreme close-up", category: "3d",
  },
  {
    id: "painting",   tag: "@olio",       label: "Pittura a Olio",  icon: "🖼️",
    thumbnailImage: "painting.jpg",
    thumbnailPrompt: "classical oil painting portrait, visible brushstrokes, rich pigments, canvas texture, old master mood, highly legible thumbnail",
    thumbnailNegativePrompt: "photograph, CGI, airbrush smoothness, animal, mascot, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "slow living-painting feel, subtle graceful drift, restrained motion",
    prompt: "classical oil painting in motion, visible brushstrokes, rich pigment texture, chiaroscuro lighting, old master composition, canvas-like painted realism",
    motion_prompt: "slow painterly motion, subtle living-painting animation, graceful camera drift, restrained movement, museum-like visual pacing",
    negative_prompt: "photograph, glossy CGI, flat vector art, clean digital realism, animal mascot", category: "art",
  },
  {
    id: "watercolor", tag: "@acquerello", label: "Acquerello",      icon: "💧",
    thumbnailImage: "watercolor.jpg",
    thumbnailPrompt: "soft watercolor landscape, visible paper grain, delicate washes, airy composition, highly legible thumbnail",
    thumbnailNegativePrompt: "hard ink, photorealistic, glossy CGI, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "soft fluid movement, gentle transitions, airy drift",
    prompt: "watercolor animation, translucent pigment washes, soft feathered edges, visible paper grain, delicate color bleeding, airy hand-painted atmosphere",
    motion_prompt: "gentle fluid motion, soft transitions, drifting camera, organic watercolor-like movement, calm lyrical pacing",
    negative_prompt: "hard ink comic lines, photorealistic texture, glossy 3D render, hyper-sharp edges", category: "art",
  },
  {
    id: "pencil",     tag: "@matita",     label: "Disegno a Matita",icon: "✏️",
    thumbnailImage: "pencil.jpg",
    thumbnailPrompt: "graphite pencil portrait sketch, cross-hatching, paper texture, monochrome drawing, highly legible thumbnail",
    thumbnailNegativePrompt: "color, photorealistic, glossy digital paint, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "subtle hand-drawn shimmer, restrained motion, sketchbook feel",
    prompt: "graphite pencil animation, fine sketch lines, cross-hatching, tonal shading, textured paper surface, monochrome hand-drawn draftsmanship",
    motion_prompt: "light sketchbook motion, subtle line shimmer, hand-drawn frame feel, restrained animation, delicate camera movement",
    negative_prompt: "full color realism, glossy CGI, watercolor wash, polished live-action", category: "art",
  },
  {
    id: "popart",     tag: "@popart",     label: "Pop Art",         icon: "🎉",
    thumbnailImage: "popart.jpg",
    thumbnailPrompt: "pop art face portrait, bold primary colors, Ben-Day dots, graphic poster contrast, highly legible thumbnail",
    thumbnailNegativePrompt: "photorealistic, muted palette, watercolor, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "graphic punchy motion, bold shape transitions, poster-like timing",
    prompt: "pop art motion graphic style, bold primary colors, Ben-Day dots, thick outlines, graphic poster contrast, screen-printed retro energy",
    motion_prompt: "graphic punchy motion, poster-like transitions, bold shape movement, rhythmic animated composition, high-impact visual timing",
    negative_prompt: "photorealistic, muted natural palette, subtle lighting realism, soft watercolor texture", category: "art",
  },
  {
    id: "cyberpunk",  tag: "@cyberpunk",  label: "Cyberpunk",       icon: "🌆",
    thumbnailImage: "cyberpunk.jpg",
    thumbnailPrompt: "cyberpunk skyline or human face, neon magenta and cyan glow, wet reflections, futuristic mood, highly legible thumbnail",
    thumbnailNegativePrompt: "sunny pastoral mood, cartoon, animal, mascot, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "rain drift, neon flicker, slow futuristic camera motion",
    prompt: "cyberpunk futuristic atmosphere, neon-lit city mood, holographic glow, wet reflective surfaces, electric magenta and cyan accents, dense urban high-tech grit",
    motion_prompt: "rain-soaked camera drift, glowing signs, atmospheric parallax, slow urban movement, volumetric haze, moody futuristic pacing",
    negative_prompt: "", category: "genre",
  },
  {
    id: "fantasy",    tag: "@fantasy",    label: "Fantasy",         icon: "🐉",
    thumbnailImage: "fantasy.jpg",
    thumbnailPrompt: "epic fantasy castle or hero silhouette, magical glow, volumetric light, simple iconic composition, highly legible thumbnail",
    thumbnailNegativePrompt: "mundane realism, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "majestic sweep, magical particles, cinematic reveal",
    prompt: "epic fantasy atmosphere, magical glow, ornate worldbuilding, volumetric light rays, enchanted palette, mythic scale, heroic high-detail visual language",
    motion_prompt: "majestic camera sweep, magical particle drift, slow epic movement, cinematic reveal, wondrous pacing, atmospheric environmental motion",
    negative_prompt: "", category: "genre",
  },
  {
    id: "horror",     tag: "@horror",     label: "Horror",          icon: "🩸",
    thumbnailImage: "horror.jpg",
    thumbnailPrompt: "horror silhouette in fog, desaturated tones, unsettling backlight, low-key atmosphere, highly legible thumbnail",
    thumbnailNegativePrompt: "bright cheerful palette, cartoon, gore, cluttered background, text, watermark, blurry",
    thumbnailMotionPrompt: "creeping camera, lingering suspense, subtle environmental movement",
    prompt: "atmospheric horror mood, eerie desaturated tones, unsettling shadows, dense fog, decayed textures, ominous contrast, psychological dread, low-key lighting",
    motion_prompt: "slow suspenseful movement, creeping camera, subtle environmental motion, lingering shots, oppressive pacing, uneasy cinematic timing",
    negative_prompt: "bright cheerful palette, cute cartoon tone, glamorous clean lighting, playful motion", category: "genre",
  },
];

/** Stili di REGIA video — definiscono come si muove la camera/il ritmo (drone, slow motion, ecc.). */
export const VIDEO_DIRECTION_STYLE_PRESETS = [
  {
    id: "cinematic", tag: "@cinematico", label: "Cinematico", icon: "🎬",
    thumbnailImage: "dir_cinematic.jpg",
    thumbnailPrompt: "cinematic movie shot with dramatic dolly movement, moody lighting, rich color grading, smooth parallax, premium film atmosphere, highly legible thumbnail",
    thumbnailNegativePrompt: "shaky camera, chaotic framing, cheap video look, overexposed",
    thumbnailMotionPrompt: "slow cinematic dolly movement, controlled framing, smooth parallax",
    prompt: "cinematic live-action look, dramatic lighting, rich color grading, atmospheric depth, filmic contrast, polished visual storytelling",
    motion_prompt: "slow cinematic dolly movement, controlled framing, smooth parallax, deliberate pacing, natural motion blur, premium film-shot rhythm",
    negative_prompt: "shaky camera, chaotic framing, cheap video look, overexposed lighting, jittery motion",
    category: "camera",
    notes: "Preset base filmico, molto versatile. Ottimo per scene narrative o emotive.",
  },
  {
    id: "slow_motion", tag: "@slowmotion", label: "Slow Motion", icon: "🐢",
    thumbnailImage: "dir_slow_motion.jpg",
    thumbnailPrompt: "slow motion human gesture, water droplets frozen mid-air, dramatic lighting, high detail, cinematic temporal smoothness, highly legible thumbnail",
    thumbnailNegativePrompt: "fast chaotic motion, time-lapse effect, jerky movement",
    thumbnailMotionPrompt: "slow motion action, stretched graceful movement, high-frame-rate feel",
    prompt: "cinematic high-detail visual clarity, dramatic lighting emphasis, elegant scene readability, polished premium footage",
    motion_prompt: "slow motion action, stretched graceful movement, high-frame-rate feel, detailed micro-motion, cinematic temporal smoothness",
    negative_prompt: "fast chaotic motion, time-lapse effect, jerky movement, handheld shake",
    category: "time",
    notes: "Serve a rallentare e valorizzare il gesto. Utile per azioni fisiche, look emotivi, reveal.",
  },
  {
    id: "timelapse", tag: "@timelapse", label: "Time-Lapse", icon: "⏩",
    thumbnailImage: "dir_timelapse.jpg",
    thumbnailPrompt: "time-lapse city skyline, fast moving clouds, rapid light transition from day to night, compressed time progression, highly legible thumbnail",
    thumbnailNegativePrompt: "slow motion, static frozen frame, realistic normal-speed motion",
    thumbnailMotionPrompt: "time-lapse motion, accelerated environmental change, fast cloud movement",
    prompt: "clean cinematic scene readability, strong environmental clarity, visually evolving atmosphere, clear long-duration visual progression",
    motion_prompt: "time-lapse motion, accelerated environmental change, fast cloud movement, rapid light transitions, compressed time progression",
    negative_prompt: "slow motion, static frozen frame, realistic normal-speed motion, handheld shake",
    category: "time",
    notes: "Perfetto per città, cieli, natura, cambi di luce, folla, costruzioni.",
  },
  {
    id: "hyperlapse", tag: "@hyperlapse", label: "Hyperlapse", icon: "🚀",
    thumbnailImage: "dir_hyperlapse.jpg",
    thumbnailPrompt: "hyperlapse travel through urban streets, rapid forward motion, stabilized perspective, energetic city progression, highly legible thumbnail",
    thumbnailNegativePrompt: "static camera, slow pacing, locked tripod shot",
    thumbnailMotionPrompt: "hyperlapse camera movement, rapid forward travel, accelerated path motion",
    prompt: "dynamic cinematic travel footage, strong perspective depth, urban or spatial progression, high visual momentum",
    motion_prompt: "hyperlapse camera movement, rapid forward travel, accelerated path motion, stabilized directional movement, energetic progression",
    negative_prompt: "static camera, slow pacing, locked tripod shot, drifting sideways without purpose",
    category: "time",
    notes: "Ottimo per spostamenti, città, corridoi, strade, transizioni spaziali forti.",
  },
  {
    id: "drone", tag: "@drone", label: "Drone", icon: "🚁",
    thumbnailImage: "dir_drone.jpg",
    thumbnailPrompt: "aerial drone shot over a coastline, expansive landscape, smooth floating camera, wide establishing view, premium travel-film atmosphere, highly legible thumbnail",
    thumbnailNegativePrompt: "handheld shake, eye-level view, cramped framing, abrupt motion",
    thumbnailMotionPrompt: "smooth aerial drone movement, gentle rise and glide, wide establishing shot",
    prompt: "aerial cinematic footage, expansive landscape readability, clean spatial composition, premium travel-film atmosphere",
    motion_prompt: "smooth aerial drone movement, gentle rise and glide, wide establishing shot, controlled cinematic sweep, stable floating camera",
    negative_prompt: "handheld shake, eye-level view, cramped framing, abrupt motion, claustrophobic composition",
    category: "camera",
    notes: "Pensato per inquadrature aeree, establishing shot, paesaggi, città, castelli, montagne.",
  },
  {
    id: "handheld", tag: "@handheld", label: "Handheld", icon: "📹",
    thumbnailImage: "dir_handheld.jpg",
    thumbnailPrompt: "handheld camera documentary shot, subtle human shake, raw immediacy, natural lighting, observational footage, highly legible thumbnail",
    thumbnailNegativePrompt: "perfect gimbal stabilization, drone sweep, slow-motion float",
    thumbnailMotionPrompt: "handheld camera motion, subtle human-operated shake, organic framing adjustments",
    prompt: "raw realistic live-action look, documentary immediacy, grounded natural lighting, immersive observational footage",
    motion_prompt: "handheld camera motion, subtle human-operated shake, organic framing adjustments, documentary realism, reactive camera behavior",
    negative_prompt: "perfect gimbal stabilization, drone sweep, slow-motion float, robotic motion",
    category: "camera",
    notes: "Per documentario, reportage, realismo, tensione, vicinanza al soggetto.",
  },
  {
    id: "gimbal", tag: "@gimbal", label: "Gimbal", icon: "🧭",
    thumbnailImage: "dir_gimbal.jpg",
    thumbnailPrompt: "gimbal-stabilized tracking shot, smooth floating camera glide, polished commercial footage, clean premium visual flow, highly legible thumbnail",
    thumbnailNegativePrompt: "handheld jitter, chaotic framing, abrupt pans",
    thumbnailMotionPrompt: "gimbal-stabilized movement, smooth tracking shot, floating camera glide",
    prompt: "clean stabilized cinematic footage, polished commercial look, balanced composition, premium smooth visual flow",
    motion_prompt: "gimbal-stabilized movement, smooth tracking shot, floating camera glide, precise cinematic motion, no shake",
    negative_prompt: "handheld jitter, chaotic framing, abrupt pans, unstable horizon",
    category: "camera",
    notes: "Perfetto per spot, walkthrough, soggetti in movimento, look moderno e premium.",
  },
  {
    id: "dolly_in", tag: "@dollyin", label: "Dolly In", icon: "🎯",
    thumbnailImage: "dir_dolly_in.jpg",
    thumbnailPrompt: "cinematic dolly push-in toward a subject, increasing emotional intensity, dramatic focus, smooth forward camera move, highly legible thumbnail",
    thumbnailNegativePrompt: "zoom jitter, random lateral movement, abrupt cuts",
    thumbnailMotionPrompt: "slow dolly in toward the subject, controlled forward camera move, increasing intensity",
    prompt: "cinematic subject emphasis, strong depth, dramatic focus, polished narrative framing",
    motion_prompt: "slow dolly in toward the subject, controlled forward camera move, increasing emotional intensity, smooth cinematic push-in",
    negative_prompt: "zoom jitter, random lateral movement, abrupt cuts, shaky handheld",
    category: "camera",
    notes: "Ottimo per reveal emotivi, tensione, importanza del personaggio o dell'oggetto.",
  },
  {
    id: "dolly_out", tag: "@dollyout", label: "Dolly Out", icon: "↩️",
    thumbnailImage: "dir_dolly_out.jpg",
    thumbnailPrompt: "cinematic dolly pull-back revealing wider environment, elegant release of space, smooth backward camera move, narrative reveal, highly legible thumbnail",
    thumbnailNegativePrompt: "chaotic shake, sudden push-in, random zoom",
    thumbnailMotionPrompt: "slow dolly out from the subject, camera pulls back smoothly, revealing wider context",
    prompt: "cinematic framing with environmental context, elegant scene depth, narrative reveal composition",
    motion_prompt: "slow dolly out from the subject, camera pulls back smoothly, revealing wider context, cinematic release of space",
    negative_prompt: "chaotic shake, sudden push-in, random zoom, unstable movement",
    category: "camera",
    notes: "Buono per reveal ambientali, chiusure scena, isolamento del soggetto.",
  },
  {
    id: "orbit", tag: "@orbit", label: "Orbit", icon: "🪐",
    thumbnailImage: "dir_orbit.jpg",
    thumbnailPrompt: "smooth orbit camera circling around a subject, 360 wraparound motion, strong parallax, dramatic subject focus, highly legible thumbnail",
    thumbnailNegativePrompt: "static tripod, random wobble, shaky handheld",
    thumbnailMotionPrompt: "smooth orbit camera around the subject, circular movement, controlled parallax",
    prompt: "cinematic subject-centered composition, strong spatial depth, visually immersive framing, premium dramatic look",
    motion_prompt: "smooth orbit camera around the subject, circular movement, controlled parallax, dynamic subject focus, cinematic wraparound motion",
    negative_prompt: "static tripod, random wobble, shaky handheld, erratic spin",
    category: "camera",
    notes: "Molto forte per personaggi, statue, prodotti, creature, soggetti iconici.",
  },
  {
    id: "push_in_macro", tag: "@macro", label: "Macro Push-In", icon: "🔍",
    thumbnailImage: "dir_macro.jpg",
    thumbnailPrompt: "extreme macro close-up of a textured surface, shallow depth of field, tactile detail, delicate focus, intimate camera movement, highly legible thumbnail",
    thumbnailNegativePrompt: "wide aerial view, shaky macro, chaotic reframing",
    thumbnailMotionPrompt: "slow macro push-in, tiny camera movement, delicate focus breathing",
    prompt: "high-detail macro cinematic look, shallow depth of field, tactile texture emphasis, extreme close-up visual richness",
    motion_prompt: "slow macro push-in, tiny camera movement, delicate focus breathing, close-detail reveal, precise intimate motion",
    negative_prompt: "wide aerial view, shaky macro, chaotic reframing, low detail",
    category: "camera",
    notes: "Per dettagli, superfici, occhi, oggetti piccoli, texture, food, beauty.",
  },
  {
    id: "rack_focus", tag: "@rackfocus", label: "Rack Focus", icon: "🎞️",
    thumbnailImage: "dir_rack_focus.jpg",
    thumbnailPrompt: "rack focus transition between foreground and background, cinematic shallow depth, elegant focus shift, lens storytelling, highly legible thumbnail",
    thumbnailNegativePrompt: "deep focus everywhere, blurry uncontrolled frame",
    thumbnailMotionPrompt: "rack focus transition between foreground and background, controlled focus shift",
    prompt: "cinematic shallow-depth imagery, elegant subject separation, polished visual hierarchy, premium lens-driven storytelling",
    motion_prompt: "rack focus transition between foreground and background, controlled focus shift, subtle camera hold, cinematic lens emphasis",
    negative_prompt: "deep focus everywhere, blurry uncontrolled frame, aggressive camera shake",
    category: "lens",
    notes: "Perfetto per enfatizzare soggetti, oggetti, relazioni visive in scena.",
  },
  {
    id: "found_footage", tag: "@foundfootage", label: "Found Footage", icon: "📼",
    thumbnailImage: "dir_found_footage.jpg",
    thumbnailPrompt: "raw found footage aesthetic, erratic handheld camera, imperfect exposure, amateur video grain, unsettling authenticity, highly legible thumbnail",
    thumbnailNegativePrompt: "perfect cinematic polish, smooth gimbal glide, luxury commercial look",
    thumbnailMotionPrompt: "erratic handheld movement, spontaneous reframing, imperfect operator motion",
    prompt: "raw amateur video aesthetic, imperfect exposure, grounded realism, unsettling authenticity, rough documentary atmosphere",
    motion_prompt: "erratic handheld movement, spontaneous reframing, imperfect operator motion, reactive camera behavior, uneasy realism",
    negative_prompt: "perfect cinematic polish, smooth gimbal glide, luxury commercial look, over-staged framing",
    category: "documentary",
    notes: "Per horror, tensione, realismi sporchi, scene immersive e nervose.",
  },
  {
    id: "documentary", tag: "@documentary", label: "Documentario", icon: "📰",
    thumbnailImage: "dir_documentary.jpg",
    thumbnailPrompt: "documentary observational shot, natural light, authentic location, shoulder-mounted camera, restrained pacing, highly legible thumbnail",
    thumbnailNegativePrompt: "music-video glamour, fantasy motion, hyper-stylized movement",
    thumbnailMotionPrompt: "subtle handheld or shoulder-mounted motion, observational framing, realistic subject follow",
    prompt: "grounded observational realism, natural light, authentic location feel, non-fiction visual language, practical realism",
    motion_prompt: "subtle handheld or shoulder-mounted motion, observational framing, realistic subject follow, restrained documentary pacing",
    negative_prompt: "music-video glamour, fantasy motion, hyper-stylized movement, impossible camera paths",
    category: "documentary",
    notes: "Più controllato di handheld puro. Ottimo per interviste, reportage, scene realistiche.",
  },
  {
    id: "surveillance", tag: "@surveillance", label: "Sorveglianza", icon: "📷",
    thumbnailImage: "dir_surveillance.jpg",
    thumbnailPrompt: "CCTV security camera view, fixed static angle, utilitarian framing, institutional grainy footage, passive observation, highly legible thumbnail",
    thumbnailNegativePrompt: "dolly shot, drone sweep, cinematic orbit, shallow depth glamour",
    thumbnailMotionPrompt: "fixed surveillance angle, locked-off static shot, minimal movement",
    prompt: "security camera aesthetic, static utilitarian framing, practical environment visibility, institutional realism",
    motion_prompt: "fixed surveillance angle, locked-off static shot, minimal movement, passive observation, no cinematic camera behavior",
    negative_prompt: "dolly shot, drone sweep, cinematic orbit, shallow depth glamour",
    category: "special",
    notes: "Per scene CCTV, controllo, registrazioni, effetti di osservazione fredda.",
  },
  {
    id: "bodycam", tag: "@bodycam", label: "Bodycam", icon: "🎥",
    thumbnailImage: "dir_bodycam.jpg",
    thumbnailPrompt: "bodycam tactical POV footage, chest-mounted camera, running bounce, first-person immersion, raw operational perspective, highly legible thumbnail",
    thumbnailNegativePrompt: "third-person orbit, drone view, elegant gimbal motion",
    thumbnailMotionPrompt: "bodycam perspective, chest-mounted camera motion, natural running bounce",
    prompt: "first-person tactical realism, grounded practical footage, immersive operational perspective, raw live-action immediacy",
    motion_prompt: "bodycam perspective, chest-mounted camera motion, natural running bounce, first-person movement, reactive framing",
    negative_prompt: "third-person orbit, drone view, elegant gimbal motion, static tripod framing",
    category: "special",
    notes: "Ottimo per immersione soggettiva, scene action, inseguimenti, tensione.",
  },
  {
    id: "first_person", tag: "@fpv", label: "First Person", icon: "👁️",
    thumbnailImage: "dir_first_person.jpg",
    thumbnailPrompt: "first-person POV shot, subjective camera perspective, direct immersive experience, realistic viewpoint, hands visible in frame, highly legible thumbnail",
    thumbnailNegativePrompt: "external third-person camera, floating detached view, drone sweep",
    thumbnailMotionPrompt: "first-person camera motion, natural head movement, subjective viewpoint",
    prompt: "immersive first-person visual perspective, direct subjective experience, grounded spatial realism, clear POV readability",
    motion_prompt: "first-person camera motion, natural head movement, subjective viewpoint, realistic viewpoint shifts, immersive embodied perspective",
    negative_prompt: "external third-person camera, floating detached view, drone sweep, static observer angle",
    category: "special",
    notes: "POV generico, utile per esperienze soggettive non tattiche.",
  },
  {
    id: "fpv_drone", tag: "@fpvdrone", label: "FPV Drone", icon: "🛸",
    thumbnailImage: "dir_fpv_drone.jpg",
    thumbnailPrompt: "FPV drone flight through architecture, fast agile aerial movement, dynamic banking turn, immersive velocity, highly legible thumbnail",
    thumbnailNegativePrompt: "static shot, slow tripod view, handheld wobble",
    thumbnailMotionPrompt: "fpv drone flight, fast agile aerial movement, dives and rises, dynamic banking turns",
    prompt: "high-speed aerial action footage, strong spatial depth, immersive flight path, dynamic cinematic geography",
    motion_prompt: "fpv drone flight, fast agile aerial movement, dives and rises, dynamic banking turns, immersive velocity",
    negative_prompt: "static shot, slow tripod view, handheld wobble, locked surveillance angle",
    category: "camera",
    notes: "Per inseguimenti, architetture, action, paesaggi ad alta energia.",
  },
  {
    id: "music_video", tag: "@musicvideo", label: "Music Video", icon: "🎵",
    thumbnailImage: "dir_music_video.jpg",
    thumbnailPrompt: "stylized music video performance shot, dramatic colored lighting, energetic camera movement, rhythmic visual flow, highly legible thumbnail",
    thumbnailNegativePrompt: "flat documentary realism, static surveillance, lifeless pacing",
    thumbnailMotionPrompt: "rhythmic camera movement, performance-oriented framing, stylish motion accents",
    prompt: "stylized performance-driven visuals, polished dramatic lighting, high visual impact, expressive contemporary video aesthetic",
    motion_prompt: "rhythmic camera movement, performance-oriented framing, stylish motion accents, dynamic pacing, energetic visual flow",
    negative_prompt: "flat documentary realism, static surveillance, lifeless pacing, awkward camera drift",
    category: "editing",
    notes: "Più energico e performativo. Ottimo per danza, moda, performance, glamour.",
  },
  {
    id: "commercial", tag: "@commercial", label: "Commercial", icon: "💎",
    thumbnailImage: "dir_commercial.jpg",
    thumbnailPrompt: "premium commercial product shot, smooth elegant camera movement, luxury lighting, aspirational visual tone, highly legible thumbnail",
    thumbnailNegativePrompt: "messy handheld, amateur framing, dirty lens feel",
    thumbnailMotionPrompt: "smooth controlled product-style camera movement, elegant pacing, refined framing",
    prompt: "premium polished commercial look, clean lighting, aspirational visual tone, luxury product-film clarity, high-end production value",
    motion_prompt: "smooth controlled product-style camera movement, elegant pacing, refined framing, clean premium motion language",
    negative_prompt: "messy handheld, amateur framing, dirty lens feel, uncontrolled motion",
    category: "editing",
    notes: "Perfetto per spot, brand feel, prodotto, beauty, food, tech.",
  },
  {
    id: "trailer", tag: "@trailer", label: "Trailer", icon: "🔥",
    thumbnailImage: "dir_trailer.jpg",
    thumbnailPrompt: "epic movie trailer shot, dramatic contrast, impactful camera push-in, bold reveal energy, high-stakes atmosphere, highly legible thumbnail",
    thumbnailNegativePrompt: "flat pacing, static amateur framing, weak dramatic motion",
    thumbnailMotionPrompt: "dramatic camera emphasis, impactful pacing, tension-building motion, cinematic push-ins",
    prompt: "epic cinematic intensity, dramatic contrast, high-stakes visual storytelling, bold trailer-grade atmosphere",
    motion_prompt: "dramatic camera emphasis, impactful pacing, tension-building motion, cinematic push-ins, strong reveal energy",
    negative_prompt: "flat pacing, static amateur framing, weak dramatic motion, casual realism",
    category: "editing",
    notes: "Più epico e d'impatto. Utile per fantasy, sci-fi, action, horror.",
  },
  {
    id: "dreamy", tag: "@dreamy", label: "Dreamy", icon: "☁️",
    thumbnailImage: "dir_dreamy.jpg",
    thumbnailPrompt: "dreamy floating camera over a misty meadow, soft luminous haze, poetic slow drift, ethereal visual mood, highly legible thumbnail",
    thumbnailNegativePrompt: "harsh documentary shake, aggressive action movement, rigid framing",
    thumbnailMotionPrompt: "floating camera drift, gentle slow pacing, soft movement, airy temporal flow",
    prompt: "soft dreamy atmosphere, luminous haze, poetic visual tone, ethereal softness, delicate cinematic mood",
    motion_prompt: "floating camera drift, gentle slow pacing, soft movement, airy temporal flow, dreamlike motion continuity",
    negative_prompt: "harsh documentary shake, aggressive action movement, rigid surveillance framing",
    category: "mood",
    notes: "Per scene poetiche, romantiche, nostalgiche, immaginifiche.",
  },
  {
    id: "chaotic", tag: "@chaotic", label: "Caotico", icon: "⚡",
    thumbnailImage: "dir_chaotic.jpg",
    thumbnailPrompt: "chaotic rapid camera movement, intense action scene, unstable framing, urgent handheld energy, frantic visual tension, highly legible thumbnail",
    thumbnailNegativePrompt: "smooth gimbal, calm pacing, static tripod, dreamy float",
    thumbnailMotionPrompt: "chaotic rapid camera movement, unstable reframing, frantic pacing, urgent handheld energy",
    prompt: "high-intensity raw action atmosphere, tense visual energy, unstable dramatic realism, urgent scene readability",
    motion_prompt: "chaotic rapid camera movement, unstable reframing, frantic pacing, urgent handheld energy, intense reactive motion",
    negative_prompt: "smooth gimbal, calm pacing, static tripod, dreamy float",
    category: "mood",
    notes: "Per fuga, panico, guerra, inseguimenti, tensione alta.",
  },
  {
    id: "loop", tag: "@loop", label: "Loop", icon: "🔁",
    thumbnailImage: "dir_loop.jpg",
    thumbnailPrompt: "seamless looping motion of a candle flame or flowing water, cyclical visual continuity, smooth start-end match, highly legible thumbnail",
    thumbnailNegativePrompt: "one-off dramatic action, abrupt ending, non-repeatable chaotic motion",
    thumbnailMotionPrompt: "seamless looping motion, repeatable gesture timing, cyclical camera movement",
    prompt: "clear visually repeatable composition, strong cyclical scene readability, simple elegant visual continuity",
    motion_prompt: "seamless looping motion, repeatable gesture timing, cyclical camera movement, smooth start-end continuity",
    negative_prompt: "one-off dramatic action, abrupt ending, non-repeatable chaotic motion, discontinuous movement",
    category: "special",
    notes: "Perfetto per mini loop, wallpaper motion, GIF-like behavior.",
  },
  {
    id: "stop_motion", tag: "@stopmotion", label: "Stop Motion", icon: "🧱",
    thumbnailImage: "dir_stop_motion.jpg",
    thumbnailPrompt: "stop-motion animation feel, handcrafted miniature scene, slightly stepped cadence, tactile frame-by-frame motion, highly legible thumbnail",
    thumbnailNegativePrompt: "hyper-smooth realistic motion, live-action fluidity, drone movement",
    thumbnailMotionPrompt: "slightly stepped stop-motion cadence, handcrafted movement timing, miniature animation feel",
    prompt: "handcrafted stop-motion visual feel, tactile miniature atmosphere, stylized practical texture, charming handmade scene design",
    motion_prompt: "slightly stepped stop-motion cadence, handcrafted movement timing, miniature animation feel, deliberate frame-by-frame motion",
    negative_prompt: "hyper-smooth realistic motion, live-action fluidity, drone movement, glossy modern camera behavior",
    category: "special",
    notes: "Per clay, miniature, toy worlds, look artigianale e illustrativo.",
  },
];

/** Retrocompatibilità: alias per codice che referenziava il vecchio nome. */
export const VIDEO_STYLE_PRESETS = VIDEO_VISUAL_STYLE_PRESETS;
